server:
  port: 9000
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:              
    url: jdbc:postgresql://tobedbinstancia.ccut3bbadl7p.us-east-1.rds.amazonaws.com:5432/tobedb?createDatabaseIfNotExist=true
    username: raquel
    password: 17092014
    driver-class-name: org.postgresql.Driver    